backend:
  name: git-gateway
  branch: roncadelle

media_folder: static/img
public_folder: /img

collections:

  ######
  # OPTIONS
  #####

  - name: options
    label: Site Options
    editor:
      preview: false
    files:
      - file: src/options/index.md
        label: SEO and site options
        name: configuration
        
        fields: 
          - label: Data type
            name: dataType
            widget: hidden
            default: options-site

          - label: SEO Section
            name: generalSeoSection
            widget: object
            fields: 
              - label: SEO Page title
                name: seoTitle
                required: false
                widget: string

              - label: SEO Page description
                name: seoDescription
                required: false
                widget: text

              - label: SEO Keywords
                name: seoKeywords
                required: false
                widget: string

              - label: Open Graph Title
                name: ogTitle
                required: false
                widget: string
              
              - label: Open Graph Image
                name: ogImage
                required: false
                widget: image

              - label: Open Graph Url
                name: ogUrl
                required: false
                widget: string
  
  - folder: src/pages/community
    label: Community
    name: users
    create: true
    fields:

    - label: Template Key
      name: templateKey
      widget: hidden
      default: user-page

    - label: SEO Section
      name: seoSection
      required: false
      widget: object
      fields: 
        - label: SEO Page title
          name: seoTitle
          required: false
          widget: string

        - label: SEO Page description
          name: seoDescription
          required: false
          widget: text

        - label: SEO Keywords
          name: seoKeywords
          required: false
          widget: string

        - label: Open Graph Title
          name: ogTitle
          required: false
          widget: string
        
        - label: Open Graph Image
          name: ogImage
          required: false
          widget: image

        - label: Open Graph Url
          name: ogUrl
          required: false
          widget: string

    - label: name
      name: title
      widget: string

    - label: User Summary
      name: userBody
      widget: text

    - label: Cover Image
      name: image
      widget: image

    - label: User Role/Professione
      name: userRole
      widget: string
    
    - label: avatar
      name: avatar
      widget: image

    - label: Service Full Content
      name: body
      widget: markdown

    - label: Blog section title
      name: newsTitle
      widget: string

    - label: Blog post tag
      name: tag
      widget: string

    - label: Instagram data 
      name: instagram
      widget: object
      fields:
        - label: username 
          name: user
          widget: string
        
    - label: Instagram Photos 
      name: instagramPhotos
      widget: list
      fields:
        - label: ID 
          name: id
          widget: string
    
    - label: User Socials
      name: socials
      widget: object
      fields: 
        - label: Instagram
          name: instagram
          widget: string
          required: false
        - label: Facebook
          name: facebook
          widget: string
          required: false
        - label: Souncloud
          name: soundcloud
          widget: string
          required: false
        - label: Spotify
          name: spotify
          widget: string
          required: false


  - folder: src/pages/services
    label: Services
    name: single-services
    create: true
    fields:

    - label: Template Key
      name: templateKey
      widget: hidden
      default: single-service-page

    - label: SEO Section
      name: seoSection
      required: false
      widget: object
      fields: 
        - label: SEO Page title
          name: seoTitle
          required: false
          widget: string

        - label: SEO Page description
          name: seoDescription
          required: false
          widget: text

        - label: SEO Keywords
          name: seoKeywords
          required: false
          widget: string

        - label: Open Graph Title
          name: ogTitle
          required: false
          widget: string
        
        - label: Open Graph Image
          name: ogImage
          required: false
          widget: image

        - label: Open Graph Url
          name: ogUrl
          required: false
          widget: string

    - label: Titolo
      name: title
      widget: string
    
    - label: Hero Section 
      name: heroSection
      widget: object
      fields:
        - label: Hero Background Image 
          name: image
          widget: image

        - label: Hero Payoff 
          name: payoff
          widget: text

    - label: Features Section title 
      name: featuresTitle
      widget: string

    - label: Features Section items 
      name: featuresList
      widget: list
      fields:

        - label: Title 
          name: title
          widget: string

        - label: Body 
          name: body
          widget: text

        - label: Cta text 
          name: cta
          widget: string

        - label: Cta url 
          name: url
          widget: string

        - label: Image 
          name: img
          widget: image

    - label: Service Full Content
      name: body
      widget: markdown

    - label: Services
      name: services
      widget: object
      fields:
        - label: Title
          name: title
          widget: string
        - label: Body
          name: body
          widget: text

    - label: Blog section
      name: latestNews
      widget: object
      fields:
        - label: Title
          name: title
          widget: string
        - label: Tag
          name: tag
          widget: string

    - label: Instagram data 
      name: instagram
      widget: object
      fields:
        - label: username 
          name: user
          widget: string
        
    - label: Instagram Photos 
      name: instagramPhotos
      widget: list
      fields:
        - label: ID 
          name: id
          widget: string
    
      
  ######
  # PAGES
  #####

  - name: pages
    label: Pages
    files:
      ######
      # HOMEPAGE
      #####
      - file: src/pages/index.md
        label: HomePage
        name: home
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: home-page
          
          - label: SEO Section
            name: seoSection
            required: false
            widget: object
            fields: 
              - label: SEO Page title
                name: seoTitle
                required: false
                widget: string

              - label: SEO Page description
                name: seoDescription
                required: false
                widget: text

              - label: SEO Keywords
                name: seoKeywords
                required: false
                widget: string

              - label: Open Graph Title
                name: ogTitle
                required: false
                widget: string
              
              - label: Open Graph Image
                name: ogImage
                required: false
                widget: image

              - label: Open Graph Url
                name: ogUrl
                required: false
                widget: string


          - label: Title (shown in Hero) 
            name: title
            hint: Titolo della pagina
            widget: string

          - label: Hero Section 
            name: heroSection
            widget: object
            fields:
              - label: Hero Background Image 
                name: image
                widget: image

              - label: Hero Payoff 
                name: payoff
                widget: text

              - label: Hero form title 
                name: formTitle
                widget: string
              
              - label: Hero Cta Services List 
                name: services
                widget: list
                fields: 
                  - label: Service Name 
                    name: HeroCtaServicesItem
                    widget: string
              
          - label: Features Section title 
            name: featuresTitle
            widget: string

          - label: Features Section items 
            name: featuresList
            widget: list
            fields:

              - label: Title 
                name: title
                widget: string

              - label: Body 
                name: body
                widget: text

              - label: Cta text 
                name: cta
                widget: string

              - label: Cta url 
                name: url
                widget: string

              - label: Image 
                name: img
                widget: image
          - label: Description Image 
            name: descriptionImage
            widget: object
            fields:
              - label: Title 
                name: title
                widget: string
              - label: Body 
                name: body
                widget: text
              - label: Image 
                name: image
                widget: image
          - label: Description Images Links 
            name: descriptionImageLinks
            widget: list
            fields:
              - label: Text 
                name: text
                widget: string
              - label: url 
                name: url
                widget: string

          - label: Team Section 
            name: team
            widget: object
            fields:
              - label: Title 
                name: title
                widget: string
              - label: Body 
                name: body
                widget: text

          - label: Services Section 
            name: services
            widget: object
            fields:
              - label: Title 
                name: title
                widget: string
              - label: Body 
                name: body
                widget: text

          - label: Latest News 
            name: latestNews
            widget: object
            fields:
              - label: Title 
                name: title
                widget: string
              - label: Blog Tag 
                name: tag
                widget: string

          - label: Form Call to action 
            name: formCta
            widget: object
            fields:
              - label: Title 
                name: title
                widget: string
              - label: Form Title 
                name: formTitle
                widget: string
              - label: Image 
                name: image
                widget: image

          - label: Form Call to action links 
            name: formCtaLinks
            widget: list
            fields:
              - label: Text 
                name: text
                widget: string
              - label: url 
                name: url
                widget: string
          - label: Instagram data 
            name: instagram
            widget: object
            fields:
              - label: username 
                name: user
                widget: string
              
          - label: Instagram Photos 
            name: instagramPhotos
            widget: list
            fields:
              - label: ID 
                name: id
                widget: string
    
      ######
      # SERVICES
      #####
      - file: src/pages/services.md
        label: Services
        name: services
        fields: 
          - label: Template Key
            name: templateKey
            widget: hidden
            default: services-page

          - label: SEO Section
            name: seoSection
            required: false
            widget: object
            fields: 
              - label: SEO Page title
                name: seoTitle
                required: false
                widget: string

              - label: SEO Page description
                name: seoDescription
                required: false
                widget: text

              - label: SEO Keywords
                name: seoKeywords
                required: false
                widget: string

              - label: Open Graph Title
                name: ogTitle
                required: false
                widget: string
              
              - label: Open Graph Image
                name: ogImage
                required: false
                widget: image

              - label: Open Graph Url
                name: ogUrl
                required: false
                widget: string
          
          - label: Title (shown in Hero) 
            name: title
            widget: string

          - label: Hero Section 
            name: heroSection
            widget: object
            fields:
              - label: Hero Background Image 
                name: image
                widget: image

              - label: Hero Payoff 
                name: payoff
                widget: text

          - label: Features Section title 
            name: featuresTitle
            widget: string

          - label: Features Section items 
            name: featuresList
            widget: list
            fields:

              - label: Title 
                name: title
                widget: string

              - label: Body 
                name: body
                widget: text

              - label: Cta text 
                name: cta
                widget: string

              - label: Cta url 
                name: url
                widget: string

              - label: Image 
                name: img
                widget: image

          - label: Services Section 
            name: services
            widget: object
            fields:
              - label: Title 
                name: title
                widget: string
              - label: Body 
                name: body
                widget: text

          - label: Latest News 
            name: latestNews
            widget: object
            fields:
              - label: Title 
                name: title
                widget: string
              - label: Blog Tag 
                name: tag
                widget: string

          - label: Instagram data 
            name: instagram
            widget: object
            fields:
              - label: username 
                name: user
                widget: string
              
          - label: Instagram Photos 
            name: instagramPhotos
            widget: list
            fields:
              - label: ID 
                name: id
                widget: string

      #######
      # COMMUNITY
      ######

      - file: src/pages/community.md
        label: Community
        name: community
        fields: 
          - label: Template Key
            name: templateKey
            widget: hidden
            default: community-page
          
          - label: SEO Section
            name: seoSection
            required: false
            widget: object
            fields: 
              - label: SEO Page title
                name: seoTitle
                required: false
                widget: string

              - label: SEO Page description
                name: seoDescription
                required: false
                widget: text

              - label: SEO Keywords
                name: seoKeywords
                required: false
                widget: string

              - label: Open Graph Title
                name: ogTitle
                required: false
                widget: string
              
              - label: Open Graph Image
                name: ogImage
                required: false
                widget: image

              - label: Open Graph Url
                name: ogUrl
                required: false
                widget: string
          
          - label: Title (shown in Hero) 
            name: title
            widget: string

          - label: Hero Section 
            name: heroSection
            widget: object
            fields:
              - label: Hero Background Image 
                name: image
                widget: image

              - label: Hero Payoff 
                name: payoff
                widget: text

          - label: Features Section title 
            name: featuresTitle
            widget: string

          - label: Features Section items 
            name: featuresList
            widget: list
            fields:

              - label: Title 
                name: title
                widget: string

              - label: Body 
                name: body
                widget: text

              - label: Cta text 
                name: cta
                widget: string

              - label: Cta url 
                name: url
                widget: string

              - label: Image 
                name: img
                widget: image

          - label: Team Section 
            name: team
            widget: object
            fields:
              - label: Title 
                name: title
                widget: string
              - label: Body 
                name: body
                widget: text

          - label: Latest News 
            name: latestNews
            widget: object
            fields:
              - label: Title 
                name: title
                widget: string
              - label: Blog Tag 
                name: tag
                widget: string

          - label: Instagram data 
            name: instagram
            widget: object
            fields:
              - label: username 
                name: user
                widget: string
              
          - label: Instagram Photos 
            name: instagramPhotos
            widget: list
            fields:
              - label: ID 
                name: id
                widget: string